apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: crm-service
  name: crm-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: crm-service
    spec:
      containers:
        #- image: crm-service
        - image: 127.0.0.1:5556/ordershop:crm
          name: crm-service
          resources: {}
      restartPolicy: Always
status: {}
