apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: customer-service
    spec:
      containers:
        #- image: customer-service
        - image: 127.0.0.1:5556/ordershop:customer
          name: customer-service
          resources: {}
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              httpHeaders:
                - name: Host
                  value: KubernetesLivenessProbe
            initialDelaySeconds: 5
            periodSeconds: 8
      restartPolicy: Always
status: {}
