FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/msg_service
WORKDIR /app/msg_service
COPY msg_service ./

ENV FLASK_APP /app/msg_service/msg_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]

