FROM 127.0.0.1:5556/ordershop:python

ENV SERVICE_NAME=gateway_api

RUN mkdir -p /app/gateway_api
WORKDIR /app/gateway_api
COPY gateway_api ./

ENV FLASK_APP /app/gateway_api/gateway_api.py

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0" ]