FROM python:3

RUN pip install flask
RUN pip install redis
RUN pip install requests
RUN pip install timeloop

RUN mkdir -p /app/product_service
RUN mkdir -p /app/lib
RUN mkdir -p /app/common

WORKDIR /app/product_service
COPY product_service ./

WORKDIR /app/lib
COPY lib ./

WORKDIR /app/common
COPY common ./

WORKDIR /app

ENV FLASK_ENV development
ENV LOGLEVEL DEBUG
ENV FLASK_APP /app/product_service/product_service.py
ENV PYTHONPATH /app

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0" ]

