FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/order_service
WORKDIR /app/order_service
COPY order_service ./

ENV FLASK_APP /app/order_service/order_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0 --debug=True" ]

