FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/inventory_service
WORKDIR /app/inventory_service
COPY inventory_service ./

ENV FLASK_APP /app/inventory_service/inventory_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]
