FROM python:3

RUN pip install redis
RUN pip install requests
RUN pip install timeloop

RUN mkdir -p /app/crm_service
RUN mkdir -p /app/lib
RUN mkdir -p /app/common

WORKDIR /app/crm_service
COPY crm_service ./

WORKDIR /app/lib
COPY lib ./

WORKDIR /app/common
COPY common ./

WORKDIR /app

ENV PYTHONPATH /app

CMD ["ls","/app"]
CMD [ "python", "/app/crm_service/crm_service.py" ]
