FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/product_service
WORKDIR /app/product_service
COPY product_service ./

ENV FLASK_APP /app/product_service/product_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]

