version: '3'
services:
  python-base:
    build:
      context: .
      dockerfile: Dockerfile-python-base
    image: 127.0.0.1:5556/ordershop:python
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
  billing-service:
    build:
      context: .
      dockerfile: Dockerfile-billing
    image: 127.0.0.1:5556/ordershop:billing
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  crm-service:
    build:
      context: .
      dockerfile: Dockerfile-crm
    image: 127.0.0.1:5556/ordershop:crm
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile-customer
    image: 127.0.0.1:5556/ordershop:customer
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    image: 127.0.0.1:5556/ordershop:gateway
    env_file:
      - ./api.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile-inv
    image: 127.0.0.1:5556/ordershop:inventory
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  msg-service:
    build:
      context: .
      dockerfile: Dockerfile-msg
    image: 127.0.0.1:5556/ordershop:msg
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
  order-service:
    build:
      context: .
      dockerfile: Dockerfile-order
    image: 127.0.0.1:5556/ordershop:order
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  product-service:
    build:
      context: .
      dockerfile: Dockerfile-product
    image: 127.0.0.1:5556/ordershop:product
    env_file:
      - ./api.env
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    image: 127.0.0.1:5556/ordershop:redis5.1
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}
