FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/billing_service
WORKDIR /app/billing_service
COPY billing_service ./

ENV FLASK_APP /app/billing_service/billing_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]

