FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/customer_service
WORKDIR /app/customer_service
COPY customer_service ./

ENV FLASK_APP /app/customer_service/customer_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]


