FROM 127.0.0.1:5556/ordershop:python

RUN mkdir -p /app/crm_service
WORKDIR /app/crm_service
COPY crm_service ./

ENV FLASK_APP /app/crm_service/crm_service.py

EXPOSE ${PORT}

CMD [ "flask", "run", "--host=0.0.0.0" ]

